<?php $this->headTitle('Contacto | Flores de Bach');?>

<br /><br />
<div id="container">

	<div class="row">
		<div class="col-sm-3"></div>
		<div class="col-sm-6 text-center">
			<h2>Cont&aacutectanos</h2>
			<p>Si tienes alguna duda, sugerencia o comentario, no dudes en contactarnos por este medio</p>
			<p><a href="mailto:feedback@startbootstrap.com">floresdebach33@yahoo.com</a>
			</p>
			<ul class="list-inline banner-social-buttons">
			</ul>
		</div>
	</div>

</div>