<div class="container">
  <div class="row">
   <div class="col-sm-1"></div>
   <div class="col-sm-10">
    <p>Las Flores de Bach son un tratamiento natural para poder combatir los niveles de estres, ansiedad, depresi&oacuten, fobias, enojo entro otros aspectos emocionales.</p></br>
  </div>
   <div class="col-sm-1"></div>
 </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <p><button href="#" class="btn btn-default btn-lg btn-test">Frasco de 30ml</button></p>
      <p>4 gotas debajo de la lengua 4 veces por d&iacutea. Tomar m&aacutes de la cuenta no supone ning&uacuten problema por intoxicaci&oacuten por sobredosis.</p>
      <p>1. - Tomar las gotas sin residuos de alimentos o bebidas de sabor en la boca.</p>
      <p>2. - No topar el gotero con los labios, cualquier residuo de saliva podr&iacutea contaminar las escencias. En caso de ocurrir esto, preferentemente limpiar el gotero con agua purificada antes de volverlo a colocar en el frasco.</p>
      <p>3. - Dejar que el l&iacutedo se absorba por si mismo debajo de la lengua.</p>
    </div>
    <div class="col-sm-4">
      <p><button href="#" class="btn btn-default btn-lg btn-test">&iquest;Qu&eacute flores tomar?</button></p>
      <p>Lo normal es que el terapeuta haga un estudio de consultante y a trav&eacutes de algunas preguntas defina qu&eacute flores son las adecuadas en cada caso, cuales son las prioritarias. Pueden incluirse hasta 7 escencias tratando hasta 7 diferentes aspectos emocionales. A lo largo del tratamiento puede necesitar revaluar esas escencias e ir cambi&aacutendolas a medida que el consultante note sus efectos y haga sus canbios.</p>
      <p>Realiza sin costo alguno de los test para determinar las flores correctas para ti.</Rea></p>
    </div>
    <div class="col-sm-4">
      <p><button href="#" class="btn btn-default btn-lg btn-test">&iquest;Cu&aacutento tiempo?</button></p>
      <p>Por lo general se recomienda que las escencias seleccionadas (todas en un frasco) se esten tomando por 3 meses. La mayor&iacutea de las veces la mejora se nota a los d&iacuteas, y algunas veces a las 2 o 3 semanas, dependiendo de la persona, pero para que ese cambio se sostenga lo recomendable es tomarlas por 3 meses. En algunos casos, cuando el problema estuvo muy arraigado o por muchos a&ntildeos, se recomienda hasta por 6 meses para que el cambio se sostenga.</p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <img class="img-responsive" src="/img/dropper_oral.jpg"/>
    </div>
    <div class="col-sm-3"></div>
  </div>
</div>
<br/>