<br /><br />
<div class="container">
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-lg-10">
      <div class="flor-description">
        <img class="img-thumbnail img-rounded" src="/img/thumbnail/agrimonia.png" />
        <h3>1. Agrimonia</h3>
        <p class="lead paragraph-flor-description">Para los que ocultan sus temores detr&aacutes de una m&aacutescara de despreocupaci&oacuten</p>
      </div>
    </div>
  </div>
<?php
  $aEsc = $this->aEscencias;
  Zend_debug::dump($aEsc);?>






</div>