<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>Las Flores de Bach son un tratamiento natural para poder combatir los niveles de estres, ansiedad, depresi&oacuten, fobias, enojo entro otros aspectos emocionales.</p></br>
    </div>
    <div class="col-sm-1"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <p class="pararaph-justified">&iquest;Qu&eacute es la terapia floral con Flores de Bach?</p>
      <p class="pararaph-justified">Es un tratamiento naturista a base de 38 escencias no farmacol&oacutegicas elaboradas a partir de agua de flores y Brandy para su conservaci&oacuten.</p>
      <p class="pararaph-justified">&iquest;C&oacutemo functionan?</p>
      <p class="pararaph-justified">Cada escencia combate un trastorno emocional o f&iacutesico diferente (impacienca, debilidad por fuerza, temor, insomnio, agresividad etc) empujando al organismo hacia la autocuraci&oacuten y equilibrio emocional.</p>
      <p class="pararaph-justified">&iquest;Qui&eacutenes pueden tomarlo?</p>
      <p class="pararaph-justified">Beb&eacutes, ni&ntildeos, embarazadas, adultos y ancianos, la que las 38 escencias no generan dependencia ni efectos secundarios.</p>
    </div>
    <div class="col-sm-6">
      <p class="pararaph-justified"><b>Contesta el Test y descubre cu&aacuteles escencias son indicadas para ti.</b></p>
      <div class="test-buttons-container">
        <a href="/test/basico"><button class="btn btn-default btn-lg btn-test-index">Test Básico</button></a>
        <a href="/test/completo"><button class="btn btn-default btn-lg btn-test-index">Test Completo</button></a>
      </div>
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/RBXUGAqD5XE"></iframe>
      </div>
    </div>
  </div>
</div>
