<?php $this->headTitle('Inicio | Flores de Bach');?>
<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>Las Flores de Bach son un tratamiento natural para eliminar problemas de estr&eacutes, ansiedad, depresi&oacuten, fobias, enojo, celos, indecisi&oacuten, y muchos problemas m&aacutes.</p></br>
      
  </div>
    <div class="col-sm-1"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
			<div>
				<p class="pararaph-justified">&iquest;Qu&eacute es la terapia floral con Flores de Bach?</p>
				<p class="pararaph-justified">Es un tratamiento naturista a base de 38 esencias no farmacol&oacutegicas elaboradas a partir de agua de flores y Brandy para su conservaci&oacuten. Su elaboraci&oacuten es hecha por centros especializados alrededor del mundo, tales como el centro Bach de Inglaterra <a href="http://www.bachflower.com" target="_blank">http://www.bachflower.com</a> y <a href="http://www.healingherbs.co.uk" target="_blank">http://www.healingherbs.co.uk</a>, entre otros.</p>
				<p class="pararaph-justified">Cada flor (esencia) de Bach tiene la capacidad de disolver un estado emocional negativo en particular y al mismo tiempo generar un estado emocional positivo opuesto. Es decir equilibra emocionalmente. Si hay enojo o intolerancia, genera calma y tolerancia, si hay inseguridad o falta de confianza, genera seguridad y confianza, si hay indecisi&oacuten genera decisi&oacuten, si hay des&aacutenimo, optimismo, si hay miedo, valor, si hay impaciencia, paciencia, etc.</p>
				<p class="pararaph-justified">Pueden eliminar problemas emocionales, de conducta, e incluso muchos transtornos de salud.</p>
				<p class="pararaph-justified">De estas 38 esencias el terapeuta en flores de bach elabora f&oacutermulas personalizadas o la formula rescue remedy.</p>
			</div>
			<div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/3cPJD-brCHQ"></iframe> 
      </div>
    </div>
    <div class="col-sm-6">
			<p><b>Obten tu f&oacutermula personalizada conteniendo hasta 7 esencias en un frasco de 30ml por solo $150 pesos mexicanos.</b></p>
      <p class="pararaph-justified"><b>Contesta el cuestionario b&aacutesico o completo y descubre qu&eacute esencias son indicadas para ti. Y si tienes hijos(as) de 2 a 12 a&ntildeos contesta el "Cuestionario Ni&ntildeos" y descubre qu&eacute esencias son indicadas para ellos.</b></p>
      <div class="test-buttons-container">
        <a href="/test/basico"><button class="btn btn-default btn-sml btn-test-index">Cuestionario Básico</button></a>
        <a href="/test/completo"><button class="btn btn-default btn-sml btn-test-index">Cuestionario Completo</button></a>
				<a href="/test/ninos"><button class="btn btn-default btn-sml btn-test-index-ninos">Cuestionario Ni&ntildeos</button></a>
      </div>
			<div class="col-sm-3">
				<p><h5>F&oacutermula personalizada: $150 pesos</h5> conteniendo desde 1 hasta un m&aacuteximo de 7 esencias seleccionadas seg&uacuten los resultados arrojados de cualquier cuestionario que hayas respondido.</p>
			</div>
			<div class="col-sm-3">
				<img style="margin-left: -25px;" src="img/bote_recortado.png" />
			</div>
			<div class="col-sm-3">
				<p><h5>Rescue remedy o remedio rescate: $150 pesos</h5> es la &uacutenica f&oacutermula para uso general. Es la combinaci&oacuten de 5 esencias que  ayudaran a sobrellevar cualquier situaci&oacuten estresante, desde los nervios antes de un examen hasta el estado de shock despu&eacutes de un accidente. La acci&oacuten de rescue remedy es casi inmediata, en segundos restaura la calma.</p>
			</div>
			<div class="col-sm-3">
				<img style="margin-left: -20px;" src="img/rescate_recorte.png" />
			</div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>Problemas donde las flores de bach han demostrado resolver con eficacia:</p>
    </div>
    <div class="col-sm-1"></div>
  </div>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-5">
      <h4>Problemas emocionales</h4>
      <ul>
        <li>Estr&eacutes</li>
        <li>Angustia</li> 
        <li>Ansiedad</li>
        <li>Depresi&oacuten</li>
        <li>Dependencia</li>
        <li>Inseguridad</li>
        <li>Desconfianza</li>
        <li>Incertidumbre</li>
        <li>Nostalgia</li>
        <li>Melancol&iacutea</li>
        <li>Resentimiento</li>
        <li>Enojo e ira</li>
        <li>Miedos y fobias
        (a lo desconocido, al cambio, a la autoridad, a hablar en p&uacuteblico, a las alturas, etc.)</li>
        <li>Sensaci&oacuten de fracaso</li>
        <li>Vergüenza</li>
        <li>Indecisi&oacuten</li>
        <li>Celos</li>
        <li>Envidia</li>
        <li>Cansancio mental y f&iacutesico</li>
        <li>Di&aacutelogo mental torturante</li>
        <li>Etc.</li>
      </ul>
    </div>
    <div class="col-sm-5">
      <h4>Problemas de conducta</h4>
      <ul>
        <li>Intolerancia a otros</li>
        <li>Hipocondr&iacuteaco(a)</li> 
        <li>Pereza</li>
        <li>Antisocial</li>
        <li>Comportamiento Obsesivo</li>
        <li>Comportamiento posesivo (en relaciones familiares o de pareja)</li>
        <li>Demandante de atenci&oacuten</li>
        <li>Pulcritud y limpieza obsesiva</li>
        <li>Timidez o fobia social</li>
        <li>Volubilidad (cambios de humor)</li>
        <li>Personalidad Influenciable</li>
        <li>Personalidad sumisa</li>
        <li>Vanidad</li>
        <li>Perfeccionismo</li>
        <li>Comportamiento Sobreprotector</li>
        <li>Obstinaci&oacuten</li>
        <li>Agresividad</li>
        <li>Rebeldía</li>
        <li>Prepotencia</li>
        <li>Indiferencia</li>
        <li>Apego excesivo</li>
        <li>Entre otros</li>
      </ul>
    </div>
    <div class="col-sm-1"></div>
  </div>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>Otros problemas que las flores de bach tratan con éxito: adicciones, problemas para dormir, trastornos de alimentación, etc.</p></br>
      
      <p class="pararaph-justified">&iquest;Qui&eacutenes pueden tomarlas?</p>
      <p class="pararaph-justified">Beb&eacutes, ni&ntildeos, embarazadas, adultos y ancianos, ya que las 38 esencias no generan dependencia ni efectos secundarios.</p>
    </div>
    <div class="col-sm-1"></div>
  </div>
</div>