<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>Las Flores de Bach son un tratamiento natural para eliminar problemas de estr&eacutes, ansiedad, depresi&oacuten, fobias, enojo, celos, indecisi&oacuten, y muchos problemas m&aacutes.</p></br>
      
  </div>
    <div class="col-sm-1"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <p class="pararaph-justified">&iquest;Qu&eacute es la terapia floral con Flores de Bach?</p>
      <p class="pararaph-justified">Es un tratamiento naturista a base de 38 escencias no farmacol&oacutegicas elaboradas a partir de agua de flores y Brandy para su conservaci&oacuten.</p>
      <p class="pararaph-justified">Las Flores de Bach tienen la capacidad de convertir una emoci&oacuten negativa en positiva</p>
      <p class="pararaph-justified">Pueden eliminar problemas emocionales, de conducta, e incluso muchos transtornos de salud</p>
    </div>
    <div class="col-sm-6">
      <p class="pararaph-justified"><b>Contesta el Test y descubre cu&aacuteles escencias son indicadas para ti.</b></p>
      <div class="test-buttons-container">
        <a href="/test/basico"><button class="btn btn-default btn-lg btn-test-index">Test Básico</button></a>
        <a href="/test/completo"><button class="btn btn-default btn-lg btn-test-index">Test Completo</button></a>
      </div>
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/RBXUGAqD5XE"></iframe>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>Problemas donde las flores de bach han demostrado resolver con eficacia:</p>
    </div>
    <div class="col-sm-1"></div>
  </div>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-5">
      <h4>Problemas emocionales</h4>
      <ul>
        <li>Estr&eacutes</li>
        <li>Angustia</li> 
        <li>Ansiedad</li>
        <li>Depresi&oacuten</li>
        <li>Dependencia</li>
        <li>Inseguridad</li>
        <li>Desconfianza</li>
        <li>Incertidumbre</li>
        <li>Nostalgia</li>
        <li>Melancol&iacutea</li>
        <li>Resentimiento</li>
        <li>Enojo e ira</li>
        <li>Miedos y fobias
        (a lo desconocido, al cambio, a la autoridad, a hablar en p&uacuteblico, a las alturas, etc.)</li>
        <li>Sensaci&oacuten de fracaso</li>
        <li>Vergüenza</li>
        <li>Indecisi&oacuten</li>
        <li>Celos</li>
        <li>Envidia</li>
        <li>Cansancio mental y f&iacutesico</li>
        <li>Di&aacutelogo mental torturante</li>
        <li>Etc.</li>
      </ul>
    </div>
    <div class="col-sm-5">
      <h4>Problemas de conducta</h4>
      <ul>
        <li>Intolerancia a otros</li>
        <li>Hipocondr&iacuteaco(a)</li> 
        <li>Pereza</li>
        <li>Antisocial</li>
        <li>Comportamiento Obsesivo</li>
        <li>Comportamiento posesivo (en relaciones familiares o de pareja)</li>
        <li>Demandante de atenci&oacuten</li>
        <li>Pulcritud y limpieza obsesiva</li>
        <li>Timidez o fobia social</li>
        <li>Volubilidad (cambios de humor)</li>
        <li>Personalidad Influenciable</li>
        <li>Personalidad sumisa</li>
        <li>Vanidad</li>
        <li>Perfeccionismo</li>
        <li>Comportamiento Sobreprotector</li>
        <li>Obstinaci&oacuten</li>
        <li>Agresividad</li>
        <li>Rebeldía</li>
        <li>Prepotencia</li>
        <li>Indiferencia</li>
        <li>Apego excesivo</li>
        <li>Entre otros</li>
      </ul>
    </div>
    <div class="col-sm-1"></div>
  </div>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>Otros problemas que las flores de bach tratan con éxito: adicciones, problemas para dormir, trastornos de alimentación, etc.</p></br>
      <p class="pararaph-justified">&iquest;C&oacutemo functionan?</p>
      <p class="pararaph-justified">Cada escencia combate un trastorno emocional o f&iacutesico diferente (impacienca, debilidad por fuerza, temor, insomnio, agresividad etc) empujando al organismo hacia la autocuraci&oacuten y equilibrio emocional.</p>
      <p class="pararaph-justified">&iquest;Qui&eacutenes pueden tomarlas?</p>
      <p class="pararaph-justified">Beb&eacutes, ni&ntildeos, embarazadas, adultos y ancianos, la que las 38 escencias no generan dependencia ni efectos secundarios.</p>
    </div>
    <div class="col-sm-1"></div>
  </div>
</div>