<?php $this->headTitle('Testimonios | Flores de Bach');?>

<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>Para nosostros es importante saber la experiencia de nuestros clientes, si has comprado con nosotros flores de bach agradecer&iacuteamos mucho que nos compartieras los resultados obtenidos.</p></br>
    </div>
    <div class="col-sm-1"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-2"></div>
      <div class="col-sm-8">
       <div class="fb-comments" data-href="http://www.floresdebach33.com/index/testimonios" data-width="700" data-numposts="5"></div>
 </div>
    <div class="col-sm-2"></div>
  </div>
</div>
