<?php
	$this->headScript()->appendFile($this->baseUrl('/js/vendor/angular.min.js','text/javascript'));
	$this->headScript()->appendFile($this->baseUrl('/js/script.js','text/javascript'));
	//echo $this->headScript();
	$this->headTitle('Test Completo | Flores de Bach');
	echo $this->headTile;
?>

<h2><?php echo($this->testTitle); //TODO make the div modal and animate?></h2>
<div ng-app="floresTest" ng-controller="testBasicoCtrl" ng-init="init(2)">

	<div ng-model="oQuestion">

		<ng-form >
			<label>{{oQuestion.i_question }}. Pregunta: {{oQuestion.vc_question}}</label>
			<div ng-repeat="options in oQuestion.a_options">
				<label><input type="radio" ng-model="oQuestion.value" value = "{{options.value}}">{{options.option}}</label>
			</div>

			<button class="btn" ng-click="sendAnswer()">Continuar >></button><br>
		</ng-form>

		Question id {{oQuestion.i_question}}
		Option value {{oQuestion.value}}
		Question group {{oQuestion.i_group}}
		Id test {{oQuestion.id_test}}

	<div id="view-content">
		<p>THIS IS THE COMPLETE <b>Test</b> and script/action name <b>complete</b></p>
</div>