<?php $this->headTitle('Cuestionarios | Flores de Bach');?>
  <section id="download" class="content-section text-center">
    <div class="download-section">
      <div class="container">
        <div class="col-lg-8 col-lg-offset-2">
          <h2>Nuestros Cuestionarios</h2>
          <p class="text-center">Realiza cualquiera de nuestros cuestionarios para definir las esencias que m&aacutes necesitas. B&aacutesico 38 preguntas, Completo 114 preguntas. O si tienes un hijo(a) de 2 a 12 a&ntildeos realiza el Cuestionario Ni&ntildeos de 38 preguntas.</p>
          <a href="/test/basico" class="btn btn-default btn-lg btn-test">Cuestionario Básico</a>
          <a href="/test/completo" class="btn btn-default btn-lg btn-test">Cuestionario Completo</a>
					<a href="/test/ninos" class="btn btn-default btn-lg btn-test">Cuestionario Ni&ntildeos</a>
        </div>
      </div>
    </div>
  </section>
<br/><br/>


