<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p><?php echo html_entity_decode($this->sResults) ?></p><br>
      <p style="font-size:18px;"><a href="/store/payment" class="btn btn-primary" style="font-size:18px;">Click aqu&iacute para ver opciones de compra</a> (S&oacute;lo M&eacute;xico)</p><br>
      <p><img src="/img/crate.jpg" style="width:100%;"></p><br>      
    </div>
    <div class="col-sm-1">
  </div>
  </div>
</div>
<br>