<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p><?php echo html_entity_decode($this->sResults) ?></p><br>
      <div class="col-sm-6">
        <p style="text-align:center"> <a href="/store/payment" class="btn btn-primary" style="font-size:18px;">Click aqu&iacute para ver opciones de compra</a></p>
        <p style="text-align:center"> (S&oacute;lo M&eacute;xico)</p>
      </div>
      <div class="col-sm-6">
        <p style="font-size:16px; font-weight:500; text-align:center;">
          Con la finalidad de mantener estos cuestionarios en linea tu donativo es importante!!
        </p>
        <div style="text-align:center">
          <form action="https://www.paypal.com/donate" method="post" target="_top">
          <input type="hidden" name="hosted_button_id" value="RA2NB2J3QAYUS" />
          <input type="image" src="https://www.paypalobjects.com/es_XC/MX/i/btn/btn_donateCC_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />
          <img alt="" border="0" src="https://www.paypal.com/es_MX/i/scr/pixel.gif" width="1" height="1" />
          </form>
        </div>
      </div>
      <div><img src="/img/crate.jpg" style="width:100%; margin-top:15px;"></div>
    </div>
    <div class="col-sm-1"></div>
  </div>
</div>
<br>