<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p><?php echo html_entity_decode($this->sResults) ?></p><br>
      <p style="font-size:18px;"><a href="/store/payment" class="btn btn-primary" style="font-size:18px;">Click aqu&iacute para ver opciones de compra</a> (S&oacute;lo M&eacute;xico)</p>
      <br>
      <p><img class="" src="//wms-na.amazon-adsystem.com/panda/20070822/US/img/a-logo-amazon.png"></p>
      <p style="font-size:16px; font-weight:500;">
        <a target="_blank" href="https://www.amazon.com.mx/b?_encoding=UTF8&tag=osmx-20&linkCode=ur2&linkId=065c473daa177d208900bb067a002394&camp=1789&creative=9325&node=9482611011">Salud, belleza y cuidado personal</a><img src="//ir-mx.amazon-adsystem.com/e/ir?t=osmx-20&l=ur2&o=34" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
      </p>
      <p style="font-size:16px; font-weight:500;">
        <a target="_blank" href="https://www.amazon.com.mx/b?_encoding=UTF8&tag=osmx-20&linkCode=ur2&linkId=e66e05d6c686a1379b6668d4deda1fb8&camp=1789&creative=9325&node=9482594011">Cocina y mejoras del hogar</a><img src="//ir-mx.amazon-adsystem.com/e/ir?t=osmx-20&l=ur2&o=34" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
      </p>
      <p><img src="/img/crate.jpg" style="width:100%;"></p><br>      
    </div>
    <div class="col-sm-1">
  </div>
  </div>
</div>
<br>