<div class="container">
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <h2>El Cuestionario ya fu&eacute contestado</h2>
      <p>Este Cuestionario ya fue completado. Si deseas registrarte y como usuario presiona el bot&oacuten de Registro abajo.</p></br>
      <a href="/user" class="btn btn-primary">Registrarme</a>
    </div>
    <div class="col-sm-2">
  </div>
  </div>
</div>
</br>