<?php $this->headTitle('Tienda | Flores de Bach');?>
  <section id="download" class="content-section text-center">
    <div class="download-section">
      <div class="container">
        <div class="col-lg-8 col-lg-offset-2">
          <h2>Tienda de Flores de Bach</h2>
          <h1>Muy pronto</h2>
          <a href="/store/payment" class="btn btn-default btn-lg btn-test">Pagos</a>
          <a href="/store/shipment" class="btn btn-default btn-lg btn-test">Envio</a>
        </div>
      </div>
    </div>
  </section>
<br/><br/>


