<?php $this->headTitle('Registro | Flores de Bach');?>

<br /><br />
<section id="test" class="content-section text-center">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h2>1 Frasco</h2>
      <br>
      <a mp-mode="dftl" href="https://www.mercadopago.com/mlm/checkout/start?pref_id=29317912-89096eae-a742-45d8-beee-7f779bdf2bed" name="MP-payButton" class='blue-ar-l-sq-mxall'>Pagar</a>
      <script type="text/javascript">
        (function(){function $MPC_load(){window.$MPC_loaded !== true && (function(){var s = document.createElement("script");s.type = "text/javascript";s.async = true;s.src = document.location.protocol+"//secure.mlstatic.com/mptools/render.js";var x = document.getElementsByTagName('script')[0];x.parentNode.insertBefore(s, x);window.$MPC_loaded = true;})();}window.$MPC_loaded !== true ? (window.attachEvent ?window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null;})();
      </script>
    </div>
  </div>
</section>
<br>
