<?php $this->headTitle('Registro | Flores de Bach');?>

<br /><br />
<section id="test" class="content-section text-center">
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-10">
    <ul style="text-align: left; font-size:22px">
      <li style="text-decoration:none;">1 frasco: Contiene las esencias de la 1 a la 6 de los resultados del test.</li>
      <li style="text-decoration:none;">2 frascos: 1er frasco contiene las esencias de la 1 a la 6 y el 2do frasco de la 7 a la 12 de los resultados del test.</li>
      <li style="text-decoration:none;">3 frascos: 1er frasco contiene las esencias de la 1 a la 6, el 2do frasco de la 7 a la 12 y el 3er frasco de la 13 a la 18 de los resultados del test.</li>
    </ul>
  </div>
  <div class="col-sm-1"></div>
</div>
  <div class="row">
    <div class="col-sm-4">
      <h3>1 Frasco $330.00 MN (env&iacuteo incluido)</h3>
      <br>
      <a mp-mode="dftl" href="https://www.mercadopago.com/mlm/checkout/start?pref_id=29317912-89096eae-a742-45d8-beee-7f779bdf2bed" name="MP-payButton" class='blue-ar-l-sq-mxall'>Pagar</a>
      <script type="text/javascript">
        (function(){function $MPC_load(){window.$MPC_loaded !== true && (function(){var s = document.createElement("script");s.type = "text/javascript";s.async = true;s.src = document.location.protocol+"//secure.mlstatic.com/mptools/render.js";var x = document.getElementsByTagName('script')[0];x.parentNode.insertBefore(s, x);window.$MPC_loaded = true;})();}window.$MPC_loaded !== true ? (window.attachEvent ?window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null;})();
      </script>
    </div>
    <div class="col-sm-4">
      <h3>2 Frascos $450.00 MN (env&iacuteo incluido)</h3>
      <br>
      <a mp-mode="dftl" href="https://www.mercadopago.com.mx/checkout/v1/redirect?preference-id=29317912-7cbe042e-de2b-4b51-b3e9-e64ee9168d8c" name="MP-payButton" class='blue-ar-l-sq-mxall'>Pagar</a>
      <script type="text/javascript">
        (function(){function $MPC_load(){window.$MPC_loaded !== true && (function(){var s = document.createElement("script");s.type = "text/javascript";s.async = true;s.src = document.location.protocol+"//secure.mlstatic.com/mptools/render.js";var x = document.getElementsByTagName('script')[0];x.parentNode.insertBefore(s, x);window.$MPC_loaded = true;})();}window.$MPC_loaded !== true ? (window.attachEvent ?window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null;})();
      </script>
    </div>
    <div class="col-sm-4">
      <h3>3 Frascos $550.00 MN (env&iacuteo incluido)</h3>
      <br>
      <a mp-mode="dftl" href="https://www.mercadopago.com.mx/checkout/v1/redirect?preference-id=29317912-455565fa-3a86-42a3-af97-36f5e4b657b1" name="MP-payButton" class='blue-ar-l-sq-mxall'>Pagar</a>
        <script type="text/javascript">
        (function(){function $MPC_load(){window.$MPC_loaded !== true && (function(){var s = document.createElement("script");s.type = "text/javascript";s.async = true;s.src = document.location.protocol+"//secure.mlstatic.com/mptools/render.js";var x = document.getElementsByTagName('script')[0];x.parentNode.insertBefore(s, x);window.$MPC_loaded = true;})();}window.$MPC_loaded !== true ? (window.attachEvent ?window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null;})();
      </script>
    </div>
  </div>
</section>
<br><br>
