<?php
  $this->headScript()->appendFile($this->baseUrl('/js/vendor/angular.min.js','text/javascript'));
  $this->headScript()->appendFile($this->baseUrl('/js/script.js','text/javascript'));
  $this->headTitle('Datos de envio | Flores de Bach');
?>
<div class="container">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6" ng-app="floresTest" ng-controller="StoreCtrl" ng-model="Message">
      <h2>Ingresa tus datos de envio</h2><br>
      <form name="form" class="" role="form">
        <div class="form-group row" ng-class="{ 'has-error': form.firstName.$dirty && form.firstName.$error.required }">
          <label class="col-sm-2 form-control-label" for="firstName">Nombre</label>
          <div class="col-sm-10">
            <input class="form-control" type="text" name="firstName" id="firstName" ng-model="firstName" required />
          </div>
          <span ng-show="form.firstName.$dirty && form.firstName.$error.required" class="help-block">Ingrese Nombre</span>
        </div>
        <div class="form-group row" ng-class="{ 'has-error': form.lastName.$dirty && form.lastName.$error.required }">
          <label class="col-sm-2 form-control-label" for="lastName">Apellido</label>
          <div class="col-sm-10">
            <input type="text" name="lastName" id="lastName" class="form-control" ng-model="lastName" required />
          </div>
          <span ng-show="form.lastName.$dirty && form.lastName.$error.required" class="help-block">Ingrese Apellido</span>
        </div>
        
        <div class="form-group row" ng-class="{ 'has-error': form.email.$dirty && form.email.$error.required }">
          <label class="col-sm-4 form-control-label" for="email">Correo Electr&oacutenico</label>
          <div class="col-sm-8">
            <input type="text" name="email" id="email" class="form-control" ng-model="email" required />
          </div>
          <span ng-show="form.email.$dirty && form.email.$error.required" class="help-block">Ingrese email</span>
        </div>

        <div class="form-group row" ng-class="{ 'has-error': form.street.$dirty && form.street.$error.required }">
          <label class="col-sm-4 form-control-label" for="street">Calle y Numero</label>
          <div class="col-sm-8">
            <input type="text" name="street" id="street" class="form-control" ng-model="street" required />
          </div>
          <span ng-show="form.street.$dirty && form.street.$error.required" class="help-block">Ingrese Calle y Numero</span>
        </div>

        <div class="form-group row" ng-class="{ 'has-error': form.colonia.$dirty && form.colonia.$error.required }">
          <label class="col-sm-4 form-control-label" for="colonia">Colonia/Area</label>
          <div class="col-sm-8">
            <input type="text" name="colonia" id="colonia" class="form-control" ng-model="colonia" required />
          </div>
          <span ng-show="form.colonia.$dirty && form.colonia.$error.required" class="help-block">Ingrese Colonia</span>
        </div>

        <div class="form-group row" ng-class="{ 'has-error': form.city.$dirty && form.city.$error.required }">
          <label class="col-sm-4 form-control-label" for="city">Ciudad</label>
          <div class="col-sm-8">
            <input type="text" name="city" id="city" class="form-control" ng-model="city" required />
          </div>
          <span ng-show="form.city.$dirty && form.city.$error.required" class="help-block">Ingrese Ciudad</span>
        </div>

        <div class="form-group row" ng-class="{ 'has-error': form.state.$dirty && form.state.$error.required }">
          <label class="col-sm-2 form-control-label" for="state">Estado</label>
          <div class="col-sm-10">
            <select label="State" id="state" name="state" ng-model="state" ng-init='state="Aguascalientes"' required >                          
              <option value="Aguascalientes">Aguascalientes</option>
              <option value="Baja California">Baja California</option>
              <option value="Baja California Sur">Baja California Sur</option>
              <option value="Campeche">Campeche</option>
              <option value="Chiapas">Chiapas</option>
              <option value="Chihuahua">Chihuahua</option>
              <option value="Coahuila">Coahuila</option>
              <option value="Colima">Colima</option>
              <option value="Distrito Federal">Distrito Federal</option>
              <option value="Durango">Durango</option>
              <option value="Estado de Mexico">Estado de México</option>
              <option value="Guanajuato">Guanajuato</option>
              <option value="Guerrero">Guerrero</option>
              <option value="Hidalgo">Hidalgo</option>
              <option value="Jalisco">Jalisco</option>
              <option value="Michoacan">Michoacán</option>
              <option value="Morelos">Morelos</option>
              <option value="Nayarit">Nayarit</option>
              <option value="Nuevo Leon">Nuevo León</option>
              <option value="Oaxaca">Oaxaca</option>
              <option value="Puebla">Puebla</option>
              <option value="Queretaro">Querétaro</option>
              <option value="Quintana Roo">Quintana Roo</option>
              <option value="San Luis Potosí">San Luis Potosí</option>
              <option value="Sinaloa">Sinaloa</option>
              <option value="Sonora">Sonora</option>
              <option value="Tabasco">Tabasco</option>
              <option value="Tamaulipas">Tamaulipas</option>
              <option value="Tlaxcala">Tlaxcala</option>
              <option value="Veracruz">Veracruz</option>
              <option value="Yucatan">Yucatán</option>
              <option value="Zacatecas">Zacatecas</option>
            </select>
          </div>
          <span ng-show="form.state.$dirty && form.state.$error.required" class="help-block">Seleccione Estado</span>
        </div>    

        <div class="form-group row" ng-class="{ 'has-error': form.zip.$dirty && form.zip.$error.required }">
          <label class="col-sm-4 form-control-label" for="street">Codigo Postal</label>
          <div class="col-sm-8">
            <input type="text" name="zip" id="zip" class="form-control" ng-model="zip" required />
          </div>
          <span ng-show="form.zip.$dirty && form.zip.$error.required" class="help-block">Ingrese Codigo Postal</span>
        </div>
        
        <div class="form-group row" ng-class="{ 'has-error': form.country.$dirty && form.country.$error.required }">
          <label class="col-sm-2 form-control-label" for="country">Pais</label>
          <div class="col-sm-10">
            <select label="Pais" id="country" name="country" ng-model="country" ng-init='country="Mexico"' required >
              <option value="Mexico">Mexico</option>
            </select>
          </div>
          <span ng-show="form.country.$dirty && form.country.$error.required" class="help-block">Seleccione Pais</span>
        </div>
        
        <div class="form-group row" ng-class="{ 'has-error': form.phoneNumber.$dirty && form.phoneNumber.$error.required }">
          <label class="col-sm-2 form-control-label" for="phoneNumber">Tel&eacutefono</label>
          <div class="col-sm-10">
            <input type="text" name="phoneNumber" id="phoneNumber" class="form-control" ng-model="phoneNumber" required />
          </div>
          <span ng-show="form.phoneNumber.$dirty && form.phoneNumber.$error.required" class="help-block">Ingrese tel&eacutefono</span>
        </div>

        <div class="form-actions">
          <button type="button" ng-click="sendAddress()" ng-disabled="form.$invalid || vm.dataLoading" class="btn btn-primary">Enviar</button>
          <img ng-if="vm.dataLoading" src="data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA==" />
          <a href="#/login" class="btn btn-danger">Cancelar</a>
          <label>{{Message}}</label>
        </div>
      </form>
    </div>
    <div class="col-sm-3"></div>
  </div>
</div>
<br><br>

