<br><br>
<section id="test" class="content-section text-center">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <h1>Gracias por su preferencia</h1>
    </div>
    <div class="col-sm-3"></div>
  </div>
  <br>
  <div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <p style="font-size:20px;">Tu orden ser&aacute enviada dentro de las siguientes 24 hrs. h&aacutebiles de haber realizado tu pago.<br>
    Nota: Si pagaste por OXXO tu orden ser&aacute enviada dentro de las siguientes 48 hrs. h&aacutebiles.</p>
  </div>
  <div class="col-sm-2"></div>
  </div>
</section>
<br><br>
