<div class="container-fluid">
  <div class="row">
    <img src="/img/02_header.jpg" class="img-responsive">
  </div>
</div>

<!-- Navigation -->
<nav class="navbar navbar-flores" role="navigation">
  <div class="container">
      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-header">
      <ul class="nav navbar-nav">
        <li>
          <a href="/index">Inicio</a>
        </li>
        <li>
          <a href="/test">Cuestionario</a>
        </li>
        <li>
          <a href="/index/esencias" >Esencias</a>
        </li>
        <li>
          <a href="/index/dosis" class="nav-text-flores">Dosis</a>
        </li>
        <li>
          <a href="/index/testimonios" class="nav-text-flores">Testimonios</a>
        </li>
        <li>
          <a href="/index/contacto" class="nav-text-flores">Contacto</a>
        </li>
      </ul>
    </div>
  </div>
    <!-- /.navbar-collapse -->
  <!-- /.container -->
</nav>


