<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta property="fb:admins" content="1738133389736276"/>
    <meta property="fb:app_id" content="243365149359480"/>
  <?php
    $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
    $this->headMeta()->appendHttpEquiv('Content-Type','text/html; charset=UTF-8')
      ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    $this->headLink()->prependStylesheet($this->baseUrl('/css/bootstrap.min.css'), 'screen',true, array('id'=>'bootstrap_stylesheet'));
    $this->headLink()->appendStylesheet($this->baseUrl('/css/overrides.css'), 'screen',true, array('id'=>'style-overrides'));
    $this->headScript()->appendFile($this->baseUrl('/js/vendor/jquery-1.12.2.min.js','text/javascript'));
    $this->headScript()->appendFile($this->baseUrl('/js/vendor/jquery.easing.min.js','text/javascript'));
    $this->headScript()->appendFile($this->baseUrl('/js/vendor/bootstrap.min.js','text/javascript'));
    echo $this->headMeta();
    echo $this->headLink();
    echo $this->headScript();
    echo $this->headTitle();
  ?>
  </head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-144964249-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-144964249-1');
  </script>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v2.6";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
    <?php
      echo $this->render('header.phtml');
      echo $this->layout()->content;
      echo $this->render('footer.phtml');
    ?>
  </body>
</html>