<?php
  $this->headScript()->appendFile($this->baseUrl('/js/vendor/angular.min.js','text/javascript'));
  $this->headScript()->appendFile($this->baseUrl('/js/script.js','text/javascript'));
  $this->headTitle('Registrar Usuario | Flores de Bach');
?>
<div class="container">
  <div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6" ng-app="floresTest" ng-controller="UserCtrl" ng-model="Message">
      <h2>Ingresa tus datos para recibir tus resultados</h2>
      <form name="form" class="" role="form">
       <div class="form-group row" ng-class="{ 'has-error': form.firstName.$dirty && form.firstName.$error.required }">
         <label class="col-sm-2 form-control-label" for="username">Nombre</label>
         <div class="col-sm-10">
          <input class="form-control" type="text" name="firstName" id="firstName"  ng-model="firstName" required />
         </div>
         <span ng-show="form.firstName.$dirty && form.firstName.$error.required" class="help-block">Ingrese Nombre</span>
       </div>
       <div class="form-group row" ng-class="{ 'has-error': form.lastName.$dirty && form.lastName.$error.required }">
        <label class="col-sm-2 form-control-label" for="username">Apellido</label>
         <div class="col-sm-10">
            <input type="text" name="lastName" id="lastName" class="form-control" ng-model="lastName" required />
         </div>
         <span ng-show="form.lastName.$dirty && form.lastName.$error.required" class="help-block">Ingrese Apellido</span>
       </div>
       <div class="form-group row" ng-class="{ 'has-error': form.email.$dirty && form.email.$error.required }">
        <label class="col-sm-4 form-control-label" for="username">Correo Electr&oacutenico</label>
        <div class="col-sm-8">
         <input type="text" name="email" id="email" class="form-control" ng-model="email" required />
        </div>
        <span ng-show="form.email.$dirty && form.email.$error.required" class="help-block">Ingrese email</span>
       </div>
        <div class="form-group row" ng-class="{ 'has-error': form.country.$dirty && form.country.$error.required }">
        <label class="col-sm-2 form-control-label" for="country">Pais</label>
         <div class="col-sm-10">
          <select label="Pais" id="country" name="country" ng-model="country" ng-init='country="Mexico"' required>
            <option value="Argentina">Argentina</option>
            <option value="Bolivia">Bolivia</option>
            <option value="Brasil">Brasil</option>
            <option value="Chile">Chile</option>
            <option value="Colombia">Colombia</option>
            <option value="Costa Rica">Costa Rica</option>
            <option value="Cuba">Cuba</option>
            <option value="Ecuador">Ecuador</option>
            <option value="El Salvador">El Salvador</option>
            <option value="Espana">España</option>
            <option value="EU">Estados Unidos</option>
            <option value="Guayana Francesa">Guayana Francesa</option>
            <option value="Granada">Granada</option>
            <option value="Guatemala">Guatemala</option>
            <option value="Guayana">Guayana</option>
            <option value="Haiti">Haití</option>
            <option value="Honduras">Honduras</option>
            <option value="Jamaica">Jamaica</option>
            <option value="Mexico" selected="selected">México</option>
            <option value="Nicaragua">Nicaragua</option>
            <option value="Paraguay">Paraguay</option>
            <option value="Panamá">Panamá</option>
            <option value="Perú">Perú</option>
            <option value="Puerto Rico">Puerto Rico</option>
            <option value="República Dominicana">República Dominicana</option>
            <option value="Surinam">Surinam</option>
            <option value="Uruguay">Uruguay</option>
            <option value="Venezuela">Venezuela </option>
          </select>
         </div>
         <span ng-show="form.country.$dirty && form.country.$error.required" class="help-block">Seleccione Pais</span>
       </div>
       <div class="form-group row" ng-class="{ 'has-error': form.phoneNumber.error.required }">
        <label class="col-sm-2 form-control-label" for="username">Tel&eacutefono</label>
         <div class="col-sm-10">
            <input type="text" name="phoneNumber" id="phoneNumber" class="form-control" ng-model="phoneNumber" />
         </div>
        <span ng-show="form.phoneNumber.$dirty" class="help-block">Ingrese tel&eacutefono (opcional)</span>
       </div>
       <div class="form-actions">
        <button type="button" ng-click="register('<?php	echo($this->idTest); ?>')" ng-disabled="form.$invalid || vm.dataLoading" class="btn btn-primary">Enviar</button>
        <img ng-if="vm.dataLoading" src="data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA==" />
        <a href="#/login" class="btn btn-danger">Cancelar</a>
        <label>{{Message}}</label>
       </div>
      </form>
    </div>
    <div class="col-sm-3"></div>
  </div>
</div>
</br></br>

