<?php $this->headTitle('Registro | Flores de Bach');?>

<br /><br />
<div id="view-content" ng-app="floresTest" ng-controller="UserCtrl">
  <h2>Register</h2>
  <form name="form" ng-submit="register("<?php echo $this->idTest; ?>")" role="form">
    <div class="form-group" ng-class="{ 'has-error': form.firstName.$dirty && form.firstName.$error.required }">
      <label for="username">First name</label>
      <input type="text" name="firstName" id="firstName" class="form-control" ng-model="firstName" required />
      <span ng-show="form.firstName.$dirty && form.firstName.$error.required" class="help-block">Ingrese Nombre</span>
    </div>
    <div class="form-group" ng-class="{ 'has-error': form.lastName.$dirty && form.lastName.$error.required }">
    <label for="username">Last name</label>
    <input type="text" name="lastName" id="lastName" class="form-control" ng-model="lastName" required />
      <span ng-show="form.lastName.$dirty && form.lastName.$error.required" class="help-block">Ingrese Apellido</span>
    </div>
    <div class="form-group" ng-class="{ 'has-error': form.lastName.$dirty && form.lastName.$error.required }">
      <label for="username">Email</label>
      <input type="text" name="email" id="email" class="form-control" ng-model="email" required />
      <span ng-show="form.email.$dirty && form.email.$error.required" class="help-block">Ingrese email</span>
    </div>
    <div class="form-group" ng-class="{ 'has-error': form.lastName.$dirty && form.lastName.$error.required }">
      <label for="username">Last name</label>
      <input type="text" name="phoneNumber" id="phoneNumber" class="form-control" ng-model="phoneNumber" required />
      <span ng-show="form.lastName.$dirty && form.lastName.$error.required" class="help-block">Ingrese tel&eacutefono</span>
    </div>
    <div class="form-actions">
      <button type="submit" ng-disabled="form.$invalid || vm.dataLoading" class="btn btn-primary">Enviar</button>
      <img ng-if="vm.dataLoading" src="data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA==" />
      <a href="#/login" class="btn btn-link">Cancel</a>
    </div>
  </form>
</div>
