/*Test table*/
INSERT INTO `FLOWERS`.`TESTS`(`VC_NME_TST`) VALUES ('Test Básico');
INSERT INTO `FLOWERS`.`TESTS`(`VC_NME_TST`) VALUES ('Test Completo');

/*QUESTIONS Table*/
/*Test 1 (Basico)*/
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Tengo miedo a caer enfermo, a la pobreza, a la muerte... o tengo fobias como insectos, muchedumbre... ','1','20','1');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Pido consejo y opinión a los demás porque cuestiono mis propias decisiones. ','1','5','2');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('No aprendo de mis experiencias, tropiezo una y otra vez con los mismos errores.','1','7','3');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me siento sin energía, no tengo fuerzas ni física ni mental, ni siquiera para salir y distraerme.','1','23','4');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Continuamente estoy dándole vueltas en mi cabeza a muchas cosas, como un disco rayado, muchas veces estos pensamientos no me dejan dormir. ','1','35','5');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Quiero que todo se haga enseguida, no soporto la lentitud, me irrita muchísimo, prefiero trabajar sólo/a. Cuando estoy enfermo/a me desespera el no recuperarme rápidamente y me pongo de mal humor.  ','1','18','6');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Cuando me siento mal o enfadado/a pongo una sonrisa y oculto mis problemas, incluso a veces hago reír a los demás. ','1','1','7');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Cuando alguien me hace algo me gustaría pagarle con la misma moneda. En muchas ocasiones siento celos, envidia, rabia…','1','15','8');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me siento desbordado/a por tantas responsabilidades, es una carga continua, tengo más trabajo del que puedo asumir. ','1','11','9');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me falta confianza en mí mismo/a, me siento inferior a otros cuando me comparo, no hago cosas por miedo al fracaso. ','1','19','10');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('He vivido situaciones muy traumáticas de las que no he conseguido sobreponerme. ','1','29','11');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me siento poco apreciado/a por las personas que quiero, aunque haga mas por ellos que por mí mismo/a.','1','8','12');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me preocupo excesivamente por los demás, sobre todo las personas más cercanas, tengo miedo a que les pase algo, tiendo a sobreproteger a los que más quiero.','1','25','13');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Suelo tener la sensación de que algo malo va a suceder, es un sentimiento de miedo inexplicable, sin causa aparente. ','1','2','14');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Creo que las cosas probablemente no tengan solución, a veces me siento como en un túnel sin salida y pienso que nada me puede ayudar. ','1','13','15');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Siento que no se qué hacer con mi vida, me siento insatisfecho/a con ella, y no sé qué dirección tomar para cambiar esto. ','1','36','16');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Busco la compañía de los demás, no me gusta la soledad, necesito hablar de mis problemas, pero si soy sincero/a apenas atiendo a las dificultades de los otros porque mis propios problemas me absorben totalmente. ','1','14','17');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Tiendo a sentirme culpable en muchas situaciones. ','1','24','18');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Tengo la sensación de haber llegado al límite de mi resistencia, estoy desesperado/a, ya no sé que hacer, siento que he tocado fondo. ','1','30','19');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Soy muy exigente conmigo mismo/a, a veces soy tan rígido/a conmigo que no me permito disfrutar de los pequeños placeres de la vida. ','1','27','20');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Siento que siempre tengo razón, me gusta tener el mando y dominar la situación y a los demás.','1','32','21');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('En muchas ocasiones me avergüenzo de mi cuerpo. Me obsesiono con las imperfecciones y olvido lo esencial. ','1','10','22');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Cumplo con todas mis obligaciones aunque eso me lleve al cansancio extremo, pero nunca me quejo. No puedo permitirme un día de descanso.','1','22','23');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Cuando alguien hace algo mal, intento convencerlo para que lo haga como debería de ser. Me frustra que no me hagan caso cuando tengo razón, a menudo esta lucha me deja sin energías','1','31','24');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Tengo pesadillas nocturnas, me quedo totalmente parado/a ante unas situación de terror, a veces diría que tengo pánico. ','1','26','25');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Tengo miedo a perder el control. Me asusta no manejar las situaciones hasta el punto de que a veces pienso que me puedo volver loco. ','1','6','26');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me desanimo fácilmente, ante cualquier mínimo obstáculo ya creo que las cosas no van a ir como había pensado, ante las dificultades de la vida me falta perseverancia para conseguir mis metas. ','1','12','27');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Recuerdo muchas veces el pasado. Lo que me hacía feliz u oportunidades que he perdido. ','1','16','28');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Estoy resignado/a, apático/a con mi vida, me gustaría cambiarla pero eso requiere demasiado esfuerzo y renuncio. ','1','37','29');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me influyen muchísimo los cambios (trabajo, pareja, domicilio...). Cuando tengo un objetivo los demás me convencen fácilmente para que cambie de idea.','1','33','30');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me irrita muchísimo los defectos de los demás, juzgo mucho a las personas. ','1','3','31');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Muchas veces siento una profunda tristeza y no sé el motivo. ','1','21','32');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me siento cansado/a por las mañanas cuando pienso en el día que me espera, aplazo muchas cosas para mañana por el propio cansancio.','1','17','33');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Muchas veces veo el vaso medio vacío, siento que la vida es injusta y sufro las consecuencias de las acciones de otras personas o situaciones ajenas a mi. ','1','38','34');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Sueño despierto/a constantemente, suelo estar en mi mundo y cuando me hablan ni me entero que me están hablando. ','1','9','35');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me cuesta muchísimo decidirme entre varias cosas o a lo largo del día mi humor varía de la alegría a la tristeza.','1','28','36');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('Me gusta distanciarme de los demás y solucionar mis propias dificultades solo/a, los demás a veces piensan que soy orgulloso o excesivamente independiente. ','1','34','37');
INSERT INTO `FLOWERS`.`QUESTIONS` (VC_CPY_QSTN,ID_TST,ID_PRDCT,I_GRP) VALUES ('No se decir que \"no\", al final acabo haciendo muchas cosas que en el fondo no deseo hacer, incluso renunciando a mis propias necesidades por complacer a los demás. ','1','4','38');

/*PRODUCTS TABLE*/

INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la ansiedad','Cuando sentimos ansiedad, tortura, desasosiego, pero nos ocultamos tras \"una mascara\" de alegría y despreocupación. Esta flor ayuda a que salgan a la superficie contenidos o traumas profundos que estaban bloqueados, nos ayuda a tomar conciencia de los conflictos y nos da la paz suficiente para superarlos');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el miedo desconocido, intangible','Cuando se tiene una sensación indeterminada de miedo y de peligro el álamo temblón te va a aportar Confianza. Disminuye los miedos y robustece la confianza interior, te da capacidad para valorar de forma realista la propia sensibilidad y mejorarla, manejándola mejor');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la Intolerancia','Cuando sentimos dentro de nosotros una actitud intolerante, tenemos tendencia a la crítica y facilidad para juzgar. Esta flor nos va a ayudar a ser compresivos e indulgentes con los demás. Nos enseña a aceptar los diversos patrones de la conducta humana y a admitir los diferentes caminos de desarrollo individual');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la falta de voluntad y sometimiento','Cuando sentimos que nuestra voluntad es débil y complaciente en grado exagerado hacia los demás. La energía de esta flor nos da una \"inyección de autoestima\", nos aporta fortaleza , y con ella aprendemos a decir \"no\" y a poner límites en función de nuestras posibilidades');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la falta de intuición','Para esos momentos en los que no tenemos confianza en nosotros mismos, desconfiamos de nuestra intuición y buscamos consejo en la opinión de los demás. Nos vemos incapaces de decidir por nosotros mismos. La energía de esta flor nos aporta confianza, seguridad y fe en la propia intuición. Te ayuda a tener opiniones definidas a decidir bien y con rapidez. Te ayuda a asumir la responsabilidad de las propias decisiones aun sabiendo que se pueden cometer errores');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el descontrol','Cuando sentimos miedo a perder el control, perder la razón, miedo a que falle la mente y tener arrebatos temperamentales incontrolables. Esta es \"la flor del autocontrol\", nos ayuda a dejar fluir las emociones dentro de un marco de pensamiento racional. Controlando los propios impulsos. Nos aporta calma y serenidad');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la falta de aprendizaje','Esta flor se relaciona con todo lo que tenga que ver con el aprendizaje, su energía nos ayuda a sacar provecho de nuestra experiencia diaria, nos aumenta la conciencia, la capacidad de observación y reflexión');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el amor condicional','Cuando nos preocupamos demasiado de las necesidades de los demás, con tendencia a cuidar en exceso a los niños, familiares y amigos, corrigiendo en exceso aquello que nos parece mal. Esta flor nos proporciona \"amor incondicional\" nos permite ser compresivos y dejar que nuestros seres queridos sean ellos mismos');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la desconexión, ensoñación','Cuando no podemos centrar la atención, nos fugamos de la realidad. Nuestro romanticismo e idealismo es exagerado hasta el punto de llegar a ser inconscientes. La energía de esta flor nos ayuda a entender que el porvenir depende del interés que pongamos en el presente, nos ayuda a mantener los pies en la tierra, a vivir el aquí y el ahora, conscientes de la realidad y de la belleza y sensibilidad que nos rodea en el momento actual');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la obsesión de limpieza y orden','Cuando tenemos un sentimiento exagerado de perfección, orden, limpieza. Esta flor actúa como una \"agente purificador\", nos ayuda a aceptarnos tal como somos, nos proporciona limpieza anímica, de mente y de cuerpo. Control y limpieza de pensamientos. Restaura el sentido de la proporción y ayuda a establecer prioridades');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el exceso de responsabilidad','Cuando dudas de tus propias  capacidades, te sientes agobiado y desbordado. El Olmo te da capacidad de aguante, calma  y responsabilidad, te ayuda en el orden, planificación y organización de las propias tareas');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el pesimismo','Cuando nos sentimos desanimados, con sensación de fracaso, escépticos, pesimistas. Es una \"depresión reactiva\", por causa conocida\". La energía positiva de la Genciana nos da confianza y fe en el desenlace positivo, nos hace comprender que el crecimiento se logra a través de experiencias y que el fracaso es una oportunidad para aprender. Nos ayuda a no claudicar porque siempre veremos \"la luz en la oscuridad\"');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la desesperanza','Cuando no encontramos razones para seguir adelante, no hay razón de vivir ni nada que te apasione. Estamos resignados y decepcionados. La energía de esta flor nos da \"la chispa inicial\" para luchar en medio de las dificultades, nos da disposición para sondear nuevos caminos a fin de conseguir lo que deseamos, con la esperanza de que todo va a tener un buen desenlace');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el Egocentrismo','Cuando nos sentimos incapaces de estar solos, tenemos una necesidad imperiosa de ser el centro de atención y sin darnos cuenta abrumamos a nuestro entorno. Esta flor nos enseña a escuchar, a pasar del monologo al diálogo, y a vivir con un carácter comunicativo y bondadoso');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para cualquier sentimiento contrario al amor: celos, rabia, envidia, odio...','Cuando tenemos una sensación de hostilidad hacia otra persona, rabia, un rechazo casi hostil. Esta es la flor de la Armonización: \"Conexión con los principios más elevados y protección contra influencias negativas, celos, envidia, rabia, etc. Que desconectan a la persona de su alma. Estar en contacto con la energía de esta flor nos hace expresar y generar amor incondicional y somos ');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la nostalgia','Cuando nos aferramos excesivamente al pasado hasta tal modo que nos impide contactar con el presente y seguir evolucionando. Esta flor nos permite dejar descansar los recuerdos para progresar mentalmente, espiritualmente y disfrutar del presente. Aceptando los cambios del curso de la vida');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el cansancio y la rutina','Cuando te falta la fuerza anímica necesaria para enfrentarte a tu vida cotidiana, esta flor te aporta vitalidad y frescura. Es el remedio del \"lunes por la mañana. La energía de esta flor es como \"una refrescante ducha fría\" que nos da armonía y equilibrio. La cabeza se aclara la percepción se aviva. Es una inyección de ánimo y aliento, particularmente ante todo lo que signifique rutina');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la impaciencia','Cuando nos sentimos acelerados, impacientes, incluso irritables. Esta flor nos aporta paciencia, calma y dulzura. Nos pone freno y relaja la mente nos ayuda a ver con absoluta claridad que todo requiere un tiempo de madurez. Nos permite ser tolerantes y pacientes con aquellas personas que son más lentas');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la falta de confianza en uno mismo','Cuando dudamos de nuestros propios valores y capacidades, tenemos sentimientos de inferioridad y expectativas de fracaso. La energía de esta flor nos aporta mayor confianza y fe en nuestras propias aptitudes, es \"una inyección de auto confianza\". Al fortalecer nuestra autoestima, somos capaces de tomar la iniciativa, asumir riesgos sin temor al fracaso y pasar a la acción, sintiéndonos satisfechos de nosotros mismos');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el miedo conocido, tangible','Cuando tenemos miedo a cosas o situaciones concretas o nos falta valor para emprender determinadas cosas. El mímulo es la flor que nos va a aportar valentía y confianza. Una vez superados los miedos, ideas que te angustian, navegaras por el mundo con jovial despreocupación y disfrutaras de la vida sin temores.\"El miedo es tu gran carcelero, pero la llave es el coraje, si la encuentras serás compasivo y libre\"');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor par la melancolía y depresión','Para cuando estamos expuestos a períodos de melancolía y tristeza, sin causa aparente que lo justifique, incluso puedes llegar a sentirte deprimido. La energía de esta flor te va a aportar felicidad y alegría de vivir. Serenidad, buen humor y estabilidad. Te ayuda a recuperar el contacto contigo mismo, con las verdaderas exigencias, te da equilibrio anímico y mental. Paz interior');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el excesivo sentido del deber','Para cuando tenemos un excesivo sentido del deber. La energía del roble te va ayudar a la moderación. Te va a permitir la entrega pero tomando conciencia de los propios límites. Te permite cuidar de ti mismo sin dejar de lado las responsabilidades. Te ayudará para que aprendas a delegar y aceptar que tu cuerpo y tu mente también necesitan reposo');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el agotamiento','Cuando nos encontramos fatigados mental y físicamente, vacíos de energía. Esta flor nos dará gran fuerza y vitalidad, nos permitirá tomar conciencia de la necesidad de descanso y aprender a reconocer nuestras propias limitaciones, equilibrando entre tensión y descanso');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la culpa','Cuando existe en nosotros una gran \"autoexigencia\", \"autoexigencia\" y sentimiento de culpa. El estado positivo de esta flor nos ayuda a comprender que \"quien retiene sus faltas y no se ama ni se perdona a sí mismo, tampoco puede amar ni perdonar a otros\". Nos ayuda a asumir nuestra responsabilidad con una actitud justa y equilibrada, nos sentimos capaces de perdonar y olvidar');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la preocupación excesiva por los seres queridos','Si nos preocupamos en exceso por los demás, y eso nos hace sentir ansiedad, temor y angustia la energía del castaño rojo nos ayuda a confiar en el destino de los demás, nos ayuda a comprender que las personas a quienes amamos tienen recursos que no imaginamos, nos dará capacidad para mantener la calma mental y física en cualquier situación de emergencia');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el terror y pánico','Para estados de sensación de terror y pánico. En situaciones extremas, casos de emergencia. Cuando nos sentimos angustiados con sensación de parálisis. Esta flor nos da confianza, coraje y determinación ante situaciones límites. Nos aporta tranquilidad, nos ayuda a afrontar las situaciones con calma y valentía, sin perder la cabeza en tiempos de crisis');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la rigidez y exceso de disciplina','Cuando estamos demasiado centrados en el propio perfeccionamiento, somos duros y rígidos con nosotros mismos. Este remedio nos aporta sobre todo flexibilidad física y mental. Nos ayuda a mantenernos flexibles de pensamiento, para que las ideas \"preconcebidas\" no nos priven de la oportunidad de obtener un conocimiento más amplio y más fresco');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la falta de equilibrio','Cuando te resulta difícil mantener tu equilibrio anímico, o incluso dudas entre dos posibles decisiones. Esta es la flor para la elección. Te da seguridad, determinación y te hace capaz de tomar decisiones rápidas convencida de la claridad y seguridad de tus objetivos en la vida');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la falta de consuelo','Cuando aun quedan en nuestro interior secuelas de traumas físicos, mentales o psíquicos, recientes o producidos hace mucho tiempo. Esta flor es la \"gran cicatrizante\" del sistema, neutraliza los acontecimientos causantes del shock y pone en marcha los mecanismos autocurativos del cuerpo. Nos aporta vitalidad y claridad mental para poder asimilar mejor los acontecimientos negativos que se produjeron');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el abatimiento extremo','Cuando nos encontramos en un estado de profunda angustia, al borde de la desesperación. Esta flor nos ayuda a serenar la mente y controlar la afluencia de pensamientos negativos. Se abre en nosotros un espacio para la luz de la esperanza, y se nos brindan nuevos conocimientos que conducen a cambios saludables');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el exceso de entusiasmo y fanatismo','Cuando nos sentimos incapaces de relajarnos, \"hiperactivos\" con tendencia a la dispersión. Esta flor nos advierte la necesidad de darnos cuenta de que las grandes cosas que hay que realizar en la vida deben ser hechas tranquila y moderadamente. Nos ayuda a vencer la tensión y el stress empleando nuestra energía con mejor orientación');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el autoritarismo','Para cuando somos tan perfeccionistas que incluso podemos llegar a ser inflexibles y autoritarios. La energía de esta flor te aporta moderación, te ayuda a afrontar que las cosas que hay que hacer en la vida deben ser hechas tranquilas y moderadamente. Sin tensión ni stress y emplear tu energía con amor y moderación');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la falta de adaptación al cambio','Cuando lo que tenemos es miedo al cambio. Esta flor nos facilita la adaptación, nos protege de la opinión de influencias externas. Te da libertad interior para poder navegar hacia nuevos horizontes. Te aporta iniciativa y valentía para empezar algo nuevo, independencia y protección frente al stress y la inestabilidad interior');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el aislamiento, soberbia','Cuando nos sentimos aislados, distanciados, la energía de esta flor nos ayuda a comprender que la comunicación con los demás es necesaria, nos ayuda a restaurar el equilibrio entre el mundo interno y externo, ampliando la capacidad de comunicación');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para los pensamientos obsesivos','Cuando tenemos pensamientos persistentes, diálogos internos torturantes, nuestro estado mental es \"de disco rayado\". La energía de esta flor nos ayuda a mantener la mente tranquila y en calma, el pensamiento controlado y la cabeza despejada. Nos permite concentrarnos en el presente con mayor claridad de pensamiento');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la insatisfacción','Cuando no sabemos lo que queremos, nuestra vocación es dudosa, nos falta definición y nos dispersamos. Esta flor es como un ancla que nos permite tener los pies en la tierra y tomar decisiones. Nos ayuda a clarificar metas y propósitos en la vida. Es la flor por excelencia del auto conocimiento');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para la apatía','Si nos falta la alegría de vivir, si nos domina la apatía interior, nos resignamos pero sentimos desmotivación y desinterés, la rosa silvestre nos provoca motivación y entusiasmo, nos hace adquirir una actitud constructiva, asumiendo mayor responsabilidad ante la propia vida y uso de su iniciativa para asumir cambios. \"Mueve las fichas, para que los cambios se produzcan\" \"Desde la apatía vives de rodillas. Para vivir hay que ponerse de pie\"');
INSERT INTO `FLOWERS`.`PRODUCTS` (`VC_PRDCT_TTL`,`TXT_PRDCT_DSCRPTN`) VALUES ('Flor para el resentimiento, amargura y autocompasion','Cuando nos sentimos amargados, \"victimas del destino\" y sin darnos cuenta culpamos a nuestro entorno de todo lo que nos pasa. La energía de la flor de sauce nos ayuda a asumir la responsabilidad sobre nuestra propia vida. A ser positivos, constructivos y optimistas, dejando que afloren a nuestra mente pensamientos positivos');


/*OPTIONS TABLE */
INSERT INTO `FLOWERS`.`OPTIONS` (`ID_TST`,`VC_OPTN_TXT`,`I_VAL`) VALUES (1,'Si, muy frecuentemente',2);
INSERT INTO `FLOWERS`.`OPTIONS` (`ID_TST`,`VC_OPTN_TXT`,`I_VAL`) VALUES (1,'A veces',1);
INSERT INTO `FLOWERS`.`OPTIONS` (`ID_TST`,`VC_OPTN_TXT`,`I_VAL`) VALUES (1,'Rara vez',0);
INSERT INTO `FLOWERS`.`OPTIONS` (`ID_TST`,`VC_OPTN_TXT`,`I_VAL`) VALUES (1,'Nunca',0);